authmn/urls.py
from django.conf.urls import patterns, include, url
from authmn import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

	url('^register/$',views.register, name='authmn_register'),
	url('^login/$',views.login, name='authmn_login'),
	url('^edit_profile/$', views.edit_profile, name='authmn_edit_profile'),
	url('^edit_user_profile/$',views.edit_user_profile,name='authmn_edit_user_profile'),
    url('^lunar_first_round/$',views.lunar_first_round),
	url('^logout/$',views.logout,name='authmn_logout'),
	url('^home/$',views.home, name='authmn_home'),
)

lunar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.simple import redirect_to

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', redirect_to, {'url': '/authmn/home'}),
    # url(r'^lunar/', include('lunar.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^authmn/', include('authmn.urls')),
)

urlpatterns += staticfiles_urlpatterns() 

authmn/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user         = models.OneToOneField(User)
    team_name    = models.CharField(max_length=20,help_text='please choose a unique team name')
    
    team_leader  = models.CharField(max_length=20,help_text='(Please enter the name of your Team leader,your team should contain atleast one member and five members at maximum)')
    member_2     = models.CharField(max_length=20,blank=True,help_text='(If you have more than one member in your team,please fill their names)')
    member_3     = models.CharField(max_length=20,blank=True,help_text='(If you have more than one member in your team,please fill their names)')
    member_4     = models.CharField(max_length=20,blank=True,help_text='(If you have more than one member in your team,please fill their names)')
    member_5     = models.CharField(max_length=20,blank=True,help_text='(If you have more than one member in your team,please fill their names)')

    team_leader_gender       = models.CharField(max_length = 1, default='M',choices = [('M','Male'),('F','Female')])
    team_leader_age          = models.IntegerField(max_length=3,help_text='(You need to be above 12 to be eligible for participating in shaastra)')
    team_leader_mobilenumber = models.CharField(max_length=12,help_text = '(Please enter your team Mobilenumber)')
    mobilenumber_2           = models.CharField(max_length=12,blank=True,help_text='(You can enter your team member mobilenumber other than team leader mobilenumber,but it is optional)')
    mobilenumber_3           = models.CharField(max_length=12,blank=True)
    mobilenumber_4           = models.CharField(max_length=12,blank=True)
    mobilenumber_5           = models.CharField(max_length=12,blank=True)
    team_leader_email = models.EmailField(max_length=40)
    email_2           = models.EmailField(max_length=40,blank=True,help_text='(You can enter your team member email_id other than team leader email,but it is optional)')
    email_3           = models.EmailField(max_length=40,blank=True)
    email_4           = models.EmailField(max_length=40,blank=True)
    email_5           = models.EmailField(max_length=40,blank=True)
    college_name = models.CharField(max_length=20,help_text= '(Please enter your college name,all your team members must be from the same college)')
    team_id = models.CharField(max_length=10)
    centre_for_first_round = models.CharField(max_length=1,default='A',choices = [('A','IIT Madras'),('B','IIT Delhi'),('C','VJTI')],help_text='(please enter your firstround allotment preference)',blank=True )
    want_accommodation = models.BooleanField(default=False)
    accomodation_for_boys = models.IntegerField(default=0, help_text='Number of male members in your team')
    accomodation_for_girls = models.IntegerField(default=0, help_text='Number of female members in your team')
    
    def __unicode__(self):
        return self.user.first_name

    class Meta:
        verbose_name = 'Team'
        verbose_name_plural = "Teams"

authmn/views.py
from authmn.forms import *
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout 
from django.contrib.auth.models import User
from authmn.models import UserProfile
from django.template import RequestContext
from django.shortcuts import *
import datetime, time
#from django.forms.widgets.CheckBoxInput import check_test

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data        
            newuser = User(username = data['team_name'],first_name = data['team_leader'],email = data['team_leader_email'])
            newuser.set_password(data['password'])
#            print ">>>> PASSWD : " , data['password']
            newuser.save()
    #       want_accommodation = check_test(data['want_accommodation'])
            userprofile = UserProfile(
                user = newuser, 
                team_leader = data['team_leader'],  
                team_name = data['team_name'],  
#                team_leader_gender = data['team_leader_gender'],
                team_leader_age = data['team_leader_age'],
                member_2 = data['member_2'],
                member_3 = data['member_3'],
                member_4 = data['member_4'],
                member_5 = data['member_5'],
                team_leader_mobilenumber = data['team_leader_mobilenumber'],
                mobilenumber_2 = data['mobilenumber_2'],
                mobilenumber_3 = data['mobilenumber_3'],
                mobilenumber_4 = data['mobilenumber_4'],
                mobilenumber_5 = data['mobilenumber_5'],
                team_leader_email = data['team_leader_email'],  
                email_2 = data['email_2'],  
                email_3 = data['email_3'],
                email_4 = data['email_4'],
                email_5 = data['email_5'],
                college_name = data['college_name'],
                team_id = "lc"+str(newuser.id), 
#                want_accommodation = data['want_accommodation'], 
#                centre_for_first_round = data['centre_for_first_round'], 
            )
            userprofile.save()
            newuser = User.objects.get(username=data['team_name'])
            newuser.username = userprofile.team_id
            newuser.save()
            user = authenticate(username = newuser.username, password=data['password'])
            auth_login(request, user)
            return redirect('authmn.views.home')
        else:
            form_errors = form.errors
            print form_errors
            
    else:
        form = RegistrationForm()
    return render_to_response('authmn/register.html', locals(),context_instance = RequestContext(request))

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            username = data['team_id']
            password = data['password']
            print " >>>>>>>>>>>>> ", username, "  ", password
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request,user)
                return redirect('authmn.views.home')
            else:
                user_profile_list = UserProfile.objects.filter(team_name=username)
                if len(user_profile_list) == 1 :
                    user_profile = user_profile_list[0]
                    username = user_profile.user.username
                    user = authenticate(username=username, password=password)
                    if user is not None:
                        auth_login(request, user)
                        return redirect('authmn.views.home')
                    else :
                        
                        error_message="Something unusual happened. We could find your Team Name, but not your Team. Contact the coordinators."
                        login_form = LoginForm()
                        return render_to_response('authmn/login.html', locals(), context_instance = RequestContext(request))
                elif len(user_profile_list) == 0 :
                    error_message="your username and password do not match"
                    login_form = LoginForm()
                    return render_to_response('authmn/login.html', locals(), context_instance = RequestContext(request))
                else :
                    error_message = "We cannot find a distinct team with that team name. Please use your team ID"
                    login_form = LoginForm()
                    return render_to_response('authmn/login.html', locals(), context_instance = RequestContext(request))
                    
    else:
        form=LoginForm()
    return render_to_response('authmn/login.html', locals(), context_instance = RequestContext(request))

def edit_profile(request):
    round_1_form = FirstRoundCentreForm()
    if request.user.is_authenticated():
        try:
            user = User.objects.get(pk=request.user.id)
        except:
            user=None
            auth_logout(request)    
            return redirect('authmn.views.login')
        if user is not None:        
            try:            
                user_profile=UserProfile.objects.get(user__id=user.id)
#                user_profile=UserProfile.objects.get(user=user)
                round_1_form.fields['centre_for_first_round'].initial = user_profile.centre_for_first_round # Set centre from user_profile
            except:
            # this would happen for admin or users created by admin without putting userprofile,so I'm not caring much about this
                return HttpResponse('Sorry you do not have a user profile')         

            
            
        if request.method == 'POST' and len(request.POST) < 10:
            round_1_form = FirstRoundCentreForm(request.POST)
            if round_1_form.is_valid():
                user_profile.centre_for_first_round = round_1_form.cleaned_data['centre_for_first_round']
                print round_1_form.cleaned_data['centre_for_first_round']
                user_profile.save()
                print user_profile.centre_for_first_round
                return redirect('authmn.views.home')
            
        elif request.method == 'POST':
            print user_profile
            form = EditProfileForm(request.POST,instance = user_profile)
            if form.is_valid():
                form.save()
                print form
                return redirect('authmn.views.home')
                #user.first_name=data['first_name']
                #user.last_name=data['last_name']
                #user.save()
                
        else:
            form = EditProfileForm(instance=user_profile)
    else:
        return redirect('authmn.views.login')
    
    return render_to_response('authmn/editprofile.html', locals(), context_instance = RequestContext(request))
    
def edit_user_profile(request):
    registered_no = UserProfile.objects.count()
    if request.user.is_authenticated:
        try:
            user=User.objects.get(pk=request.user.id)
        except:
            user=None
            auth_logout(request)    
            return redirect('authmn.views.login')
        if request.method == 'POST':
            form=EditUserForm(request.POST,instance=user)
            if form.is_valid():
                form.save()
                return redirect('authmn.views.home')
        else:
            form=EditUserForm(instance=user)
    else:
        return redirect('authmn.views.home')
    return render_to_response('edituser.html', locals(), context_instance = RequestContext(request))

def lunar_first_round(request):
    registered_no = UserProfile.objects.count()
    form=FirstRoundCentreForm()
    if request.user.is_authenticated:
        user=request.user
        try:
            userprofile=UserProfile.objects.get(user=user)
        except:
            user=None
            auth_logout(request)    
            return redirect('authmn.views.login')
        if request.method == 'POST':
            form=FirstRoundCentreForm(request.POST)
            if form.is_valid():
                userprofile.centre_for_first_round = form.cleaned_data['centre_for_first_round']
                return redirect('authmn.views.home')
    
    else:
        return redirect('authmn.views.home')
    return render_to_response('firstround.html', locals(), context_instance = RequestContext(request))
                 
def logout(request):
    if request.user.is_authenticated():
        auth_logout(request)
    else:
        return redirect('authmn.views.login')
    return redirect('authmn.views.login')

def home(request):
    #start date, end date and today's date in seconds for the clock
    (startDate, endDate, now) = set_clock_date()
    registered_no = UserProfile.objects.count()
    round_1_form = FirstRoundCentreForm()
    
    if request.user.is_authenticated:
        if request.user.is_superuser: # For admin to see table of users
            users_for_template = UserProfile.objects.all()
            return render_to_response('authmn/admin.html', locals(), context_instance=RequestContext(request))
        
        user = request.user
        try:
            user_profile = UserProfile.objects.get(user=user)
        except:
            user_profile = None
            user = None
            auth_logout(request)

        if user_profile:
            round_1_form = FirstRoundCentreForm()
            round_1_form.fields['centre_for_first_round'].initial = user_profile.centre_for_first_round # Set centre from user_profile
            
            if request.method == 'POST':
                round_1_form = FirstRoundCentreForm(request.POST)
                if round_1_form.is_valid():
                    user_profile.centre_for_first_round = round_1_form.cleaned_data['centre_for_first_round']
                    print round_1_form.cleaned_data['centre_for_first_round']

templates/authmn/admin.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
    <title>Admin | LRC</title>

    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" media="all">

    <link href="{% static 'datatables/table_style.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'datatables/TableTools.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'datatables/TableTools_JUI.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/jui_themes/smoothness/jquery-ui-1.10.3.custom.css' %}" rel="stylesheet" media="screen">

    
    <script type="text/javascript" src="{% static 'js/jquery-1.8.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui-1.10.3.custom.min.js' %}"></script>
    <script src="{% static 'datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'datatables/TableTools.js' %}"></script>
    <script src="{% static 'datatables/ZeroClipboard.js' %}"></script>
    <!-- <script src="{% static 'dataTables.bootstrap.js' %}"></script>
            JQuery UI looks better than bootstrap version-->
</head>

<body>
    <div class="container-fluid">
        
        <!-- /////////////////////////////////////////////////////////
                                Datatable
            \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
        <div class="row-fluid">
            <div class='span12'></div>
        </div>
        <div class="row-fluid">
            <div class='span12' style='width:200%'>
                  <table class="table table-bordered table-hover display" id="user_table" width="100%">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Team Name</th>
                          <th>College</th>
                          <th>Center1</th>
                          <th>Leader</th>
                          <th>Member2</th>
                          <th>Member3</th>
                          <th>Member4</th>
                          <th>Member5</th>
                          <th>Leader Ph</th>
                          <th>Member2 Ph</th>
                          <th>Member3 Ph</th>
                          <th>Member4 Ph</th>
                          <th>member5 Ph</th>
                          <th>Leader Email</th>
                          <th>Member2 Email</th>
                          <th>Member3 Email</th>
                          <th>Member4 Email</th>
                          <th>Member5 Email</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for u in users_for_template %}
                          <tr>
                          <td>{{u.team_id}}</td>
                          <td>{{u.team_name}}</td>
                          <td>{{u.college_name}}</td>
                          <td>{% if u.centre_for_first_round == 'A' %}IITM
                            {%elif u.centre_for_first_round == 'B'%}IITB
                            {%elif u.centre_for_first_round == 'C'%}VJTI
                            {%endif%}
                          </td>
                          <td>{{u.team_leader}}</td>
                          <td>{{u.member_2}}</td>
                          <td>{{u.member_3}}</td>
                          <td>{{u.member_4}}</td>
                          <td>{{u.member_5}}</td>
                          <td>{{u.team_leader_mobilenumber}}</td>
                          <td>{{u.mobilenumber_2}}</td>
                          <td>{{u.mobilenumber_3}}</td>
                          <td>{{u.mobilenumber_4}}</td>
                          <td>{{u.mobilenumber_5}}</td>
                          <td>{{u.team_leader_email}}</td>
                          <td>{{u.email_2}}</td>
                          <td>{{u.email_3}}</td>
                          <td>{{u.email_4}}</td>
                          <td>{{u.email_5}}</td>
                          </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                

                <script>
                    var oTable = null;
                    
                    function show_table(oTable_element) { // show and initialize datatable
                        if( oTable != null )    oTable.fnDestroy() // delete last instance of table
                        
                        
                        /* Get all columns with buttons and handle them in Searches and printing
                        var cols = Array(), cols_table_tools = Array()
                            th_cols = oTable_element.getElementsByTagName("thead")[0].getElementsByTagName("th")
                            cols_len = th_cols.length
                        for ( var col_i = 0; col_i < cols_len; col_i++ ) {
                            // For universality between tables, get length from the table elements itself.
                            if( ! $(th_cols[col_i]).hasClass('button_in_table') ) {
                                cols.push(null);
                                cols_table_tools.push(col_i)
                            } else {
                                cols.push({ "bSearchable": false }); // for Edit/Del & Subtask adding buttons
                            }
                        }
                        */
                        
                        oTable = $(oTable_element).dataTable( { // Initializes the table with necessary params
                            "bJQueryUI" : true, // let jqueryUI handle rendering
                            "bLengthChange" : false, // Don't show dropdown for number of entries to show on one page
                            "bFilter" : true, // On the fly Search text-field on top right
                            "bSort" : true, // Sorting by clicking on table header
                            "bAutoWidth": true, // Auto fit the table columns
                            "oLanguage": { "sSearch": "" } , // Remove the Search Label (for the text-field)
                        //    "aoColumns": cols, // Choose which columns are used in Filter(Search) [[ needed to ignore button columns ]]
                            "sDom": 'R<C>H<"clear"><"ui-toolbar ui-widget-header ui-corner-tl ui-corner-tr ui-helper-clearfix"lfr>tT<"ui-toolbar ui-widget-header ui-corner-bl ui-corner-br ui-helper-clearfix"ip>',
                            "oTableTools": {
                                "sSwfPath": "/static/datatables/swf/copy_csv_xls_pdf.swf",
                                "aButtons": [ {
                                        "sExtends": "copy",
                                        //"mColumns": cols_table_tools
                                    },
                                    {
                                        "sExtends": "csv",
                                        //"mColumns": cols_table_tools
                                    },
                                    {
                                        "sExtends": "pdf",
                                        //"mColumns": cols_table_tools
                                    },//"xls" 
                                ]
                            }
                            /*
                             * The sDom is a complicated line. It holds what all is there on 
                             * the table based on some coded html :P
                             * basics : <"#aaa"> means add a div tag with id 'aaa' in that location
                             *          <"aaa"> means add a div tag with class 'aaa' in that location
                             *          R, <C>, H etc are inbuilt things for header, and stuff ... 
                             *          t - table, f - filter-text-input, 
                             *          ui-widget-header, etc are classes which jquery uses for the top-bar
                             * 
                             * For a better reference, look in the data-tables website for sDom
                             */
                        } );
                        
                    }
                    
                    show_table($("#user_table"))
                    
                    
                </script>


            </div>
        </div>
        <div class="row-fluid">
            <div class='span12'></div>
        </div>
        <div class="row-fluid">
            <center>
                <div class="btn-group span6 offset3">
                    <a class='btn' href="{% url authmn_logout %}">Logout</a>
                    <a class='btn' href="{% url admin:index %}">Admin</a>
                </div>
            </center>

            
        </div>
    </div>
</body>
</html>

templates/authmn/editprofile.html
{% extends "authmn/index.html" %}

{% block login_content_block %}
    <div class="row-fluid container_page slide-right" id="profile_content">
        <div class="offset1 span3" id="left_content">
        </div>
        <div class="span6 white scroll-pane" id="right_content">
            <button type="button" class="close close_white" onclick="$('#home_menu').click();">&times;</button>
            <br><br>
            <h3> Edit Team Details </h3>

            <div id="editprofile_section">
                <form action="" method="POST">
                    {% csrf_token %}
                    <center><h3 class="white" for="id-user">User : {{ user }}</h3></center>
                    <table>
                        {{ form.as_table }}
                        <tr>
                            <td colspan="2"><center><input class="btn" value="Submit" type="submit" /></center></td>
                        </tr>
                    </table>
                </form>
                
            </div>
        </div>
    </div>

    <style type="text/css">
        table, td, th{
            border:1px solid transparent; 
            padding:5px; 
            position:relative;
            top:-5px;
        }
    </style>

    <script type="text/javascript">
        $(document).ready(function(){
            $("#profile_menu").click();
            $(".close").bind('click', function(e){
                url = $('#home_menu').attr('href');
                window.open(url,'_self');
            });
        });
    </script>
{% endblock %}

{% block home_menu_block %}
    <li class="menu-item">
        <a id="home_menu" href="{% url authmn_home %}">
            Home<br /><span class="sub"></span>
        </a>
    </li>
{% endblock %}
{% block login_menu_block %}
    <li class="menu-item current-menu-item">
        <a href="#" id="profile_menu" onclick="show_page(this.id)">
            Profile<br /><span class="sub"></span>
        </a>
    </li>
{% endblock %}

templates/authmn/edituser.html
<html>
<title> edit profile </title>
<body>
<p><label for="id-user">user:{{ user }}</label>
	<input id="id_user" type="hidden"></p>
<a href="{% url authmn_edit_user_profile %}">change my user profile</a>
{{ value|linebreaks }}
<p>first_name={{ first_name }}</p>
<p>last_name={{ last_name }}</p>
<p>email= {{ email }}</p>
<form action="" method="POST">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="change_my_profile">
</form>
<a href="{% url authmn_logout %}">logout</a>
</body>
</html>

templates/authmn/login.html
{% extends "authmn/index.html" %}

{% block login_content_block %}
    <div class="row-fluid container_page slide-right" id="login_content">
        <div class="offset1 span3" id="left_content">
        </div>
        <div class="span6 white scroll-pane" id="right_content">
            <button type="button" class="close close_white" onclick="$('#home_menu').click();">&times;</button>
            <br><br>
            <h3> Login </h3>
            <div id="login_section">
                <form action ="" method="POST">
                        {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    <p> {{ error_message }} </p>
                    {{ value|linebreaks }} 

                    <input type="submit" value="Login" class="btn btn-inverse" style="position:relative; left:80%">
                </form>
            </div>
        </div>
    </div>

    <style type="text/css">
        table, td, th{
            border:1px solid transparent; 
            padding:5px; 
            position:relative;
            top:-5px;
        }
    </style>

    <script type="text/javascript">
        $(document).ready(function(){
            $("#login_menu").click();
            $(".close").bind('click', function(e){
                url = $('#home_menu').attr('href');
                window.open(url,'_self');
            });
        });
    </script>
{% endblock %}

{% block home_menu_block %}
    <li class="menu-item">
        <a id="home_menu" href="{% url authmn_home %}">
            Home<br /><span class="sub"></span>
        </a>
    </li>
{% endblock %}
{% block login_menu_block %}
    <li class="menu-item current-menu-item">
        <a href="#" id="login_menu" onclick="show_page(this.id)">
            Login<br /><span class="sub"></span>
        </a>
    </li>
{% endblock %}
    <!--</body>
</html>-->

templates/authmn/register.html
<!--<html> 
    <head>
	<b>registration</b>
    </head>
    <body>-->
{% extends "authmn/index.html" %}

{% block login_content_block %}
    <div class="row-fluid container_page slide-right" id="register_content">
        <div class="offset1 span3" id="left_content">
            <center>
            </center>
        </div>
        <div class="offset2 span8 white scroll-pane" id="right_content">
            <button type="button" class="close close_white" onclick="$('#home_menu').click();">&times;</button>
            <br><br>
            <h3> Register </h3>
<!--            <form action ="" method="POST">
                {% csrf_token %}
                <table id="registration_table">
                    {{ form.as_table }}
                </table>
                <br />
                <center>
                    <input type="submit" value="Register" class="btn btn-inverse">
                </center>
            </form>-->
            <h3> Sorry, registrations are over ! <br /></h3>
<center>            <h5> Best of luck to those who got selected !</h5></center>
        </div>
    </div>

    <style type="text/css">
        table ,tr, td , th {
            border-top:2px solid white; 
            padding:10px; 
            position:relative;
            top:-5px;
        }
    </style>

    <script type="text/javascript">
        $(document).ready(function(){
            $("#register_menu").click();
            $(".close").bind('click', function(e){
                url = $('#home_menu').attr('href');
                window.open(url,'_self');
            });
        });
    </script>
    {% if team_id %}
        <div id="team_id_alert">
            <center>
                    <p style="font-size:20px; color:#ff5725">Your Team ID is <strong>{{team_id}}</strong>. Use this ID for logging in.</p><br>
                    <a href="{% url authmn_login %}" class="btn btn-inverse">Login</a> &nbsp; &nbsp;
                    <a href="{% url authmn_home %}" class="btn btn-inverse">Home</a>
            </center>
        </div>
        
        <script type="text/javascript">
            $("#team_id_alert").bPopup({
                    //position: [350, 150],
                    speed: 450,
                    easing: 'ease-in',
                    opacity: 0.95,
                });
        </script>
    {% endif %}
{% endblock %}

{% block home_menu_block %}
    <li class="menu-item">
        <a id="home_menu" href="{% url authmn_home %}">
            Home<br /><span class="sub"></span>
        </a>
    </li>
{% endblock %}
{% block login_menu_block %}
    <li class="menu-item current-menu-item">
        <a href="#" id="register_menu" onclick="show_page(this.id)">
            Register<br /><span class="sub"></span>
        </a>
    </li>
{% endblock %}

    <!-- </body>
</html> -->